# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - uses: sbt/setup-sbt@v1
    - name: Run tests
      run: sbt test package
    - name: Check for target
      run: |
        ls -lad target/scala*
        ls -lad target/scala-2.13/*.jar
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mybuild.jar
        path: target/scala-2.13/tracks_2.13-0.1.0-SNAPSHOT.jar
        if-no-files-found: error
